export enum CallState {
    INCOMING_CALL = 'INCOMING_CALL',
    OUTGOING_CALL = 'OUTGOING_CALL',
    REJECTED_CALL = 'REJECTED_CALL',
    CANCELLED_CALL = 'CANCELLED_CALL',
    ACCEPTED_CALL = 'CALL_ACCEPTED'
}
